//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eonup.Remote.Service.RemoteSearchService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RemoteSearchService.ISearchService")]
    public interface ISearchService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/Query", ReplyAction="http://tempuri.org/ISearchService/QueryResponse")]
        string Query(System.Collections.Generic.List<int> Ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/Query", ReplyAction="http://tempuri.org/ISearchService/QueryResponse")]
        System.Threading.Tasks.Task<string> QueryAsync(System.Collections.Generic.List<int> Ids);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISearchServiceChannel : Eonup.Remote.Service.RemoteSearchService.ISearchService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchServiceClient : System.ServiceModel.ClientBase<Eonup.Remote.Service.RemoteSearchService.ISearchService>, Eonup.Remote.Service.RemoteSearchService.ISearchService {
        
        public SearchServiceClient() {
        }
        
        public SearchServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SearchServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Query(System.Collections.Generic.List<int> Ids) {
            return base.Channel.Query(Ids);
        }
        
        public System.Threading.Tasks.Task<string> QueryAsync(System.Collections.Generic.List<int> Ids) {
            return base.Channel.QueryAsync(Ids);
        }
    }
}
